project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - papers.qmd
    - garden.qmd

website:
  title: "Erich Trieschman"
  description: "Personal site"
  navbar:
    background: "#2d4a3e"   # dark green banner
    foreground: "#ffffff"
    left:
      - href: index.qmd
        text: Home
      - href: papers.qmd
        text: Papers
      - href: garden.qmd
        text: Garden
    page-footer:
      - icon: github
        href: https://github.com/etrieschman
        aria-label: GitHub
    # page-footer:
    #   background: "#1f3d2b"
    #   foreground: "#ffffff"
    #   left: "© 2026 Erich Trieschman"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    linkcolor: "#1a5fb4"
    smooth-scroll: true
    code-fold: true
    code-tools: false
